version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pip"
    directory: "/scriptlets/test-executions-rerunner"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pip"
    directory: "/cert-tools/snapstore"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pip"
    directory: "/cert-tools/toolbox"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pip"
    directory: "/cert-tools/launcher"
    schedule:
      interval: "weekly"
