[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "launcher"
version = "0.1.0"
requires-python = ">=3.8"

[project.scripts]
stacker = "launcher.stacker:main"

[project.optional-dependencies]
dev = ["pytest"]
