name: Submit a job to Testflinger
on:
    push:
        branches: [CERTTF-330-test-testflinger-submit]
    workflow_dispatch:

jobs:
  testflinger-submit:
    runs-on: [self-hosted, testflinger]
    steps:
    - name: Checkout tools repo
      uses: actions/checkout@v4
    - name: Submit job
      id: submit
      uses: canonical/testflinger/.github/actions/submit@CERTTF-424-attachment-reference-directory
      with:
        poll: true
        job: |
          job_queue: hp-elitebook-850-g7-notebook-pc
          test_data:
            attachments:
              - local: install_tools.sh
              - local: scriptlets
            test_cmds: |
              #!/usr/bin/env bash
              set -x
              ls -al
    - name: Display job id
      run: |
        echo "The ID of the submitted job was ${{ steps.submit.outputs.id }}"
          
