name: Test the toolbox package
on:
  push:
    branches-ignore:
      - 'main'
    paths:
      - 'cert-tools/toolbox/**'
      - '.github/workflows/test_toolbox.yaml'
concurrency:
  # Cancel inprogress runs if new commit pushed
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  test-package:
    name: Test the toolbox package
    runs-on: [self-hosted, jammy, x64]
    defaults:
      run:
        working-directory: cert-tools/toolbox
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: "3.8"
      - run: pip install .[dev]
      - run: pytest
