name: Submit testflinger jobs for test

on:
  push:
    branches:
      - fix-submit-bug
  workflow_dispatch:

jobs:
  testflinger-submit-test:
    runs-on: [self-hosted, testflinger]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Submit job
        id: submit
        uses: canonical/testflinger/.github/actions/submit@fix-submit-bug
        with:
          poll: true
          job: |
            job_queue: 202405-34052
            provision_data:
              url: https://tel-image-cache.canonical.com/oem-share/dud.img.xz
      - name: Display Job
        run: |
          echo "The id of the submitted job was ${{ steps.submit.outputs.id }}"