name: Test Scriptlets
on:
  push:
    branches-ignore:
      - 'main'
    paths:
      - 'scriptlets/**'
      - '.github/workflows/test_scriptlets.yaml'
# Cancel inprogress runs if new commit pushed
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  test-bash-scripts:
    runs-on: [self-hosted, linux, large, jammy, x64]
    defaults:
      run:
        working-directory: scriptlets/tests
    steps:
      - uses: actions/checkout@v4
      - run: sudo apt install bats -y
      - run: bats .
  test-rerunner-script:
    runs-on: [self-hosted, linux, large, jammy, x64]
    defaults:
      run:
        working-directory: scriptlets/test-executions-rerunner
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: "3.8"
      - run: pip install tox
      - run: tox